### PR TITLE
supports 100+ llms, added configs on sidebar

### PR DESCRIPTION
**Pull request by tikendraw**
1. Supports most of the llms out there (via litellm)
2.  Cconfigs support 

(delete the ollama class and merge this)

### CODE REVIEW

**Comment by tcsenpai** [comment]
I have no experience with LiteLLM.

I saw that the commits removed Groq and Perplexity handlers too: is that intentional?

Also:  the clean message part is specific to Perplexity due to some quirks in their API specifications

I'd like to keep cloud LLMs too (Groq and Perp now, others in the future) so once that is confirmed and Ollama is still supported through LiteLLM I will be happy to merge it.

**Comment by tikendraw** [comment]
Is it working with other llms ? Gemini/openai?

**Comment by tcsenpai** [comment]
> Is it working with other llms ? Gemini/openai?

I am not sure as I don't have any key for Gemini/OpenAI

In your tests, it works with them? If so, I would use your fork as a base and start working on that if you are ok with it

**Comment by tcsenpai** [comment]
Can you take a look at [this commit](https://github.com/tcsenpai/multi1/commit/1cbbe4c6d413745803360485cbf08af661f628e7) and see if it is ok for you to replace this PR with that commit?

**Comment by tikendraw** [comment]
> After some testing:
> 
> I see the advantage. Unfortunately, there are some things that seem to be broken:
> 
> * (minor) litellm in requirements.txt
> * Tested with ollama/gemma2:2b and I get
> 
> image
> 
> And that results in empty steps being show in the UI.
> 
> I think there is some problem with that. Could you please test it with ollama locally (and, if you have access to other apis, also with those)?

Ollama's local llms are producing bad output, that is causing the json parsing issues.

**Comment by tcsenpai** [comment]
Seems to work better with the current prompt + litellm implementation, by the way thanks for the idea that I implemented

**Pull request closed without merging**
